import {
  LayoutDashboard, Compass, BrainCircuit, FlaskConical, Users, ShieldAlert, Sparkles,
  BarChart3, FileText, Settings, ListChecks, Target, Kanban, Bot, User,
  Banknote, TrendingUp, Wallet, TrendingDown, Bell, Search, Moon, Sun, LogOut,
  ChevronDown, Plus, Check, X, ArrowUpRight, ArrowDownRight,
  Download, Upload, Mail, Lock, ShieldCheck, Edit, Trash2, Filter, Calendar,
  Clipboard, Folder, Globe, Database, Key, Camera, Phone, Building2, CreditCard,
  PieChart, Activity, MessageSquare, Send, Mic, Layers, Clock, CheckCircle2,
  AlertTriangle, ChevronsRight, Building, RefreshCw, Paperclip, MoreHorizontal,
  Circle, Menu, type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  compass: Compass,
  "brain-circuit": BrainCircuit,
  "flask-conical": FlaskConical,
  users: Users,
  "shield-alert": ShieldAlert,
  sparkles: Sparkles,
  "bar-chart-3": BarChart3,
  "file-text": FileText,
  settings: Settings,
  "list-checks": ListChecks,
  target: Target,
  kanban: Kanban,
  bot: Bot,
  user: User,
  banknote: Banknote,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  wallet: Wallet,
  bell: Bell,
  search: Search,
  moon: Moon,
  sun: Sun,
  "log-out": LogOut,
  "chevron-down": ChevronDown,
  plus: Plus,
  check: Check,
  x: X,
  "arrow-up-right": ArrowUpRight,
  "arrow-down-right": ArrowDownRight,
  download: Download,
  upload: Upload,
  mail: Mail,
  lock: Lock,
  "shield-check": ShieldCheck,
  edit: Edit,
  trash: Trash2,
  filter: Filter,
  calendar: Calendar,
  clipboard: Clipboard,
  folder: Folder,
  globe: Globe,
  database: Database,
  key: Key,
  camera: Camera,
  phone: Phone,
  building2: Building2,
  building: Building,
  "credit-card": CreditCard,
  "pie-chart": PieChart,
  activity: Activity,
  "message-square": MessageSquare,
  send: Send,
  mic: Mic,
  layers: Layers,
  clock: Clock,
  "check-circle": CheckCircle2,
  "alert-triangle": AlertTriangle,
  "chevrons-right": ChevronsRight,
  "refresh-cw": RefreshCw,
  paperclip: Paperclip,
  "more-horizontal": MoreHorizontal,
  circle: Circle,
  menu: Menu,
};

export function DynamicIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[name] ?? Sparkles;
  return <Icon className={className} />;
}
